# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc24931fb2d37a8d224389a54e4b5440d0f0e65e2703bd3913cc34ab3b7c586530847402b1ebbfa56035dd75ddc0b94d08256d277868c40ddfa959271bfb7c64

test:
  secret_key_base: 764bf13a8d8f48f96c85e6d2e55b6ebc545b31877e7ec314ed7a4d5b427e81ab26e97ceed6c2836c92ec688ecb9655d8d0b6f36dc3d3f90402ff45cafd408830

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
